Revert tunneling CLI changes from master
databricks/databricks-cli pull request #424
Opened 2022-02-01 18:55 UTC by deka108

Tunneling CLI will be moved to development mode.

2022-02-01 19:10 UTC, jaipreet-s requested changes

2022-02-01 19:10 UTC, jaipreet-s commented on databricks_cli/sdk/version.py
> +API_VERSIONS=['2.0', '2.1']
We can leave these as there should be a space between '='

2022-02-01 19:10 UTC, jaipreet-s commented on lint.sh
> -fi
Again, I'm OK leaving these in as these help isolate py2 vs py3 dependencies

2022-02-01 19:10 UTC, jaipreet-s commented on tox.ini
> +	./lint.sh
Same comment here re: py2 vs py3

2022-02-01 19:31 UTC, joveyuan-db approved these changes

2022-02-01 19:31 UTC, joveyuan-db commented on databricks_cli/sdk/api_client.py
> +            return self.url + self.jobs_api_version + path
If this doesn't make a re-revert difficult, we can probably remove the extra whitespace here.

2022-02-02 00:06 UTC, jaipreet-s approved these changes

2022-02-02 00:06 UTC, merged