Add tags to create_job, and add an update_job function to the sdk
databricks/databricks-cli pull request #457
Opened 2022-05-06 01:50 UTC by ari-nz

2022-05-06 09:07 UTC, nfx requested changes

2022-05-06 09:07 UTC, nfx commented on databricks_cli/sdk/service.py
> +    def update_job(self, job_id, new_settings, fields_to_remove=None, headers=None, version=None):
@ari-nz please also cover the corner cases with additional unit tests.

2022-05-10 01:11 UTC, ari-nz commented
@nfx  - I've added a few more tests. Let me know if there's anything else specific that you need.

2022-07-20 01:34 UTC, ari-nz commented
@nfx I've rebased this fork back onto the latest version of main. It looks like the `create_job` api has been updated, but not the `update_job`

Requesting this PR to be merged

2022-07-20 01:36 UTC, ari-nz commented
Tagging @pietern too as it looks like you've been actively lately :)

2022-08-18 14:04 UTC, pietern commented
@ari-nz Thanks for the ping. We've picked up generating `service.py` from an internal definition of the API as of a couple of months ago, which is why the updated version of `create_job` appeared. I'll perform a regeneration and include `update_job` and pull in your tests.

2022-08-18 14:34 UTC, closed without merging