[SEC-6587] Databricks CLI Tool Config File inherits default system umask
databricks/databricks-cli pull request #522
Opened 2022-07-26 16:06 UTC by shreyas-goenka

This PR makes changes so that .databrickscfg file has user only read write permissions at create time rather than creation file -> write token -> change permission to user only read write (0o600) which can be used by an adversary to read the token

Tested manually by looking that the permissions on the file after its creation

2022-07-27 09:13 UTC, fjakobs requested changes
Code change looks good but please also add a unit test to `tests/configure/test_provider.py` to verify that the file permissions are indeed 600.

2022-08-01 11:27 UTC, fjakobs approved these changes

2022-08-01 12:52 UTC, merged

2022-08-10 13:13 UTC, pietern commented
@shreyas-goenka Did you test or hypothesize how this works on Windows? It looks risky / like it might break on Windows.

2022-08-10 13:52 UTC, shreyas-goenka commented
@pietern I did not think about this testing on windows. A quick look at the docs leads me to believe the happy path most should be fine i.e. when no `.databrickscfg` file exists and users use the cli, one with the right permissions should be created. 

I believe this because 
1. `os.open`: works for both windows and unix
2. `os.path.exists`: The os availability is not specified in the docs but very highly likely it works on both systems
3. Before my code we had `os.chmod` calls which did not break this workflow (Only true if a user actually used windows with our cli and it worked :P)

In any case the python os docs don't make it clear what the behavior would be here. Do we have windows VM to do a quick test?

2022-08-10 14:02 UTC, pietern commented
Yes, I'll be in touch with details.

2022-08-10 14:05 UTC, fjakobs commented
Why not just add `windows` to the test matrix in https://github.com/databricks/databricks-cli/blob/main/.github/workflows/push.yml#L21 ?

2022-08-11 12:07 UTC, pietern commented
@fjakobs We should, once 1) existing failing tests on Windows are fixed, and 2) we trim the # of builds (no need to test all Python versions on Windows, just 1 of them would be sufficient). Thinking about 2), it's probably easier to define a dedicated Windows test job...